version: "3"

volumes:
  mysql-server:
  backend-server:

services:
  mysql-server:
    image: mysql
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: employee_DB
      MYSQL_ROOT_PASSWORD: 1001
    ports:
      - 3306:3306
    volumes:
      - mysql-server:/var/lib/mysql-server
  backend-server:
    container_name: backend-server
#    image: backend-server
    build: .
    environment:
      - MYSQL_HOST=mysql-server
      # - MYSQL_HOST=employeeNetwork
    ports:
      - "8081:8081"
    volumes:
      - backend-server:/var/lib/backend-server




