version: "3"

volumes:
  backend:

services:
  employee-backend-h2-db:
    container_name: employee-backend-h2-db
    image: employee-backend-h2-db
    build:
      context: .
    ports:
      - "8081:8081"
    volumes:
      - backend:/var/lib/employee-backend