version: "3"

volumes:
  employeeDB:
  employee-backend:

services:
  employee-backend:
    container_name: employee-backend
    image: employee-backend
    build:
      context: .
    ports:
      - "8081:8081"
    volumes:
      - employee-backend:/var/lib/employee-backend




